# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.srcs/sources_1/ip/temperatureSensor/temperatureSensor.xci
# IP: The module: 'temperatureSensor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.gen/sources_1/ip/temperatureSensor/temperatureSensor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temperatureSensor'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.gen/sources_1/ip/temperatureSensor/temperatureSensor.xdc
# XDC: The top module name and the constraint reference have the same name: 'temperatureSensor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.srcs/sources_1/ip/temperatureSensor/temperatureSensor.xci
# IP: The module: 'temperatureSensor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.gen/sources_1/ip/temperatureSensor/temperatureSensor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temperatureSensor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/XilinxProjects/SeniorCapstone/SeniorCapstone.gen/sources_1/ip/temperatureSensor/temperatureSensor.xdc
# XDC: The top module name and the constraint reference have the same name: 'temperatureSensor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
